openapi: 3.0.0
info:
  title: siastats.info API
  version: 2019-10-03
servers:
- description: Navigator (blockchain explorer) API
  url: https://siastats.info:3500/navigator-api
- description: Hosts monitor API
  url: https://siastats.info:3510/hosts-api
- description: Daily-updated databases, Real-Time databases, and Mining pools Luck
    and other stats
  url: https://siastats.info/
tags:
- name: navigator
- name: host
paths:
  /hash/{hash}:
    get:
      operationId: hash
      parameters:
      - description: hash or block height
        explode: false
        in: path
        name: hash
        required: true
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/HashResponse'
                type: array
          description: Successful Response
        default:
          content:
            text/plain:
              schema:
                type: string
          description: Unexpected error
      servers:
      - url: https://siastats.info:3500/navigator-api
      summary: Returns the information about any hash (address, Tx, contract...) or
        block height on the blockchain
      tags:
      - navigator
  /status:
    get:
      operationId: status
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Status'
                type: array
          description: Successful Response
        default:
          content:
            text/plain:
              schema:
                type: string
          description: Unexpected error
      servers:
      - url: https://siastats.info:3500/navigator-api
      summary: Global status and blockchain sync situation of SiaStats nodes
      tags:
      - navigator
  /host/{id}:
    get:
      operationId: host
      parameters:
      - description: SiaStats host ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HostResponse'
          description: Successful Response
        default:
          content:
            text/plain:
              schema:
                type: string
          description: Unexpected error
      servers:
      - url: https://siastats.info:3510/hosts-api
      summary: Information and detailed SiaStats benchmarks about a host.
      tags:
      - host
  /allhosts:
    post:
      operationId: allHosts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AllHostsRequest'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Host'
                type: array
          description: Successful Response
        default:
          content:
            text/plain:
              schema:
                type: string
          description: Unexpected error
      servers:
      - url: https://siastats.info:3510/hosts-api
      summary: Summary information and SiaStats final scores of all the hosts in the
        Sia network.
      tags:
      - host
components:
  schemas:
    Status:
      example:
        lastblock: 6
        heartbeat: 1
        peers: 5
        consensusblock: 0
        version: version
      properties:
        consensusblock:
          type: integer
        lastblock:
          type: integer
        heartbeat:
          format: int64
          type: integer
        peers:
          type: integer
        version:
          type: string
      type: object
    Transaction:
      example:
        MasterHash: MasterHash
        TxType: TxType
        ScChange: 7.061401241503109
        SfChange: 9.301444243932576
        Height: 3
        Timestamp: Timestamp
      properties:
        MasterHash:
          type: string
        ScChange:
          format: double
          type: number
        SfChange:
          type: number
        Height:
          type: integer
        Timestamp:
          type: string
        TxType:
          type: string
      type: object
    Benchmarks:
      example:
        latencyScore: 1
        finalScore: 6
        errorDescription: errorDescription
        benchFailureRate: 6
        errorType: errorType
        latency: 7
        downScore: 9
        contractSuccess: true
        errorFull: errorFull
        up: 4
        down: 9
        upScore: 5
      properties:
        finalScore:
          type: integer
        latency:
          type: integer
        latencyScore:
          type: integer
        up:
          format: int64
          type: integer
        upScore:
          type: integer
        down:
          format: int64
          type: integer
        downScore:
          type: integer
        contractSuccess:
          type: boolean
        benchFailureRate:
          type: integer
        errorType:
          type: string
        errorDescription:
          type: string
        errorFull:
          type: string
      type: object
    ComparisonMatrix:
      example:
        price: 9.018348186070783
        contractPrice: 1.284659006116532
        stored: 8
        up: 3.5571952270680973
        collateral: 6.438423552598547
        down: 6.965117697638846
      properties:
        stored:
          type: integer
        price:
          type: number
        collateral:
          type: number
        up:
          type: number
        down:
          type: number
        contractPrice:
          type: number
      type: object
    Ticks:
      example:
        total:
        - - 2.8841621266687802
          - 2.8841621266687802
        - - 2.8841621266687802
          - 2.8841621266687802
        bandwidth:
        - - 5.944895607614016
          - 5.944895607614016
        - - 5.944895607614016
          - 5.944895607614016
        used:
        - - 6.778324963048013
          - 6.778324963048013
        - - 6.778324963048013
          - 6.778324963048013
        storage:
        - - 6.878052220127876
          - 6.878052220127876
        - - 6.878052220127876
          - 6.878052220127876
        collateral:
        - - 6.704019297950036
          - 6.704019297950036
        - - 6.704019297950036
          - 6.704019297950036
      properties:
        total:
          items:
            items:
              type: number
            type: array
          type: array
        used:
          items:
            items:
              type: number
            type: array
          type: array
        storage:
          items:
            items:
              type: number
            type: array
          type: array
        bandwidth:
          items:
            items:
              type: number
            type: array
          type: array
        collateral:
          items:
            items:
              type: number
            type: array
          type: array
      type: object
    PlotBand:
      example:
        color: color
        from: 3
        to: 3
        label:
          textAlign: textAlign
          rotation: 7
          x: 0
          y: 7
          text: text
          align: align
      properties:
        color:
          type: string
        from:
          format: int64
          type: integer
        to:
          format: int64
          type: integer
        label:
          $ref: '#/components/schemas/PlotBand_label'
      type: object
    RegionalScore:
      example:
        latencyScore: 0
        finalScore: 7
        latency: 6
        downScore: 8
        up: up
        region: region
        down: down
        upScore: 4
      properties:
        region:
          type: string
        latency:
          type: integer
        up:
          type: string
        down:
          type: string
        latencyScore:
          type: integer
        upScore:
          type: integer
        downScore:
          type: integer
        finalScore:
          type: integer
      type: object
    Host:
      example:
        Pubkey: Pubkey
        CurrentIp: CurrentIp
        TotalStorage: 6.027456183070403
        UploadPrice: 7
        Collateral: 5
        Rank: 3
        AcceptingContracts: true
        DownloadPrice: 9
        FinalScore: 2
        ErrorType: ErrorType
        Version: Version
        UsedStorage: 1.4658129805029452
        ContractPrice: 5
        Id: 0.8008281904610115
        StoragePrice: 2
        Online: true
        CountryCode: CountryCode
      properties:
        Id:
          type: number
        Online:
          type: boolean
        Pubkey:
          type: string
        CurrentIp:
          type: string
        CountryCode:
          type: string
        TotalStorage:
          type: number
        AcceptingContracts:
          type: boolean
        Version:
          type: string
        UsedStorage:
          type: number
        Collateral:
          type: integer
        ContractPrice:
          type: integer
        StoragePrice:
          type: integer
        UploadPrice:
          type: integer
        DownloadPrice:
          type: integer
        Rank:
          type: integer
        FinalScore:
          type: integer
        ErrorType:
          type: string
      type: object
    HashResponse:
      example:
        MasterHash: MasterHash
        Type: Type
        balanceSc: 0.8008281904610115
        firstSeen: 2
        balanceSf: 5.962133916683182
        receivedSc: 6.027456183070403
        sentSc: 1.4658129805029452
        TotalTxCount: 5
        last100Transactions:
        - MasterHash: MasterHash
          TxType: TxType
          ScChange: 7.061401241503109
          SfChange: 9.301444243932576
          Height: 3
          Timestamp: Timestamp
        - MasterHash: MasterHash
          TxType: TxType
          ScChange: 7.061401241503109
          SfChange: 9.301444243932576
          Height: 3
          Timestamp: Timestamp
      properties:
        Type:
          type: string
        MasterHash:
          type: string
        balanceSc:
          format: double
          type: number
        receivedSc:
          format: double
          type: number
        sentSc:
          format: double
          type: number
        balanceSf:
          type: number
        TotalTxCount:
          type: integer
        firstSeen:
          type: integer
        last100Transactions:
          items:
            $ref: '#/components/schemas/Transaction'
          type: array
      type: object
    AllHostsRequest:
      example:
        list: list
        network: network
      properties:
        network:
          type: string
        list:
          type: string
      required:
      - list
      - network
      type: object
    HostResponse:
      example:
        minContractPrice: 7.386281948385884
        isp: isp
        lon: 1.4658129805029452
        seenBy:
        - seenBy
        - seenBy
        network: network
        uptime6m: 3.0576100241049344
        totalStorage: 2.3021358869347655
        windowSize: 1
        uptime1m: 3.0205796992916243
        countryCode: countryCode
        regionalScores:
        - latencyScore: 0
          finalScore: 7
          latency: 6
          downScore: 8
          up: up
          region: region
          down: down
          upScore: 4
        - latencyScore: 0
          finalScore: 7
          latency: 6
          downScore: 8
          up: up
          region: region
          down: down
          upScore: 4
        rank: 6
        id: 0
        benchmarks:
          latencyScore: 1
          finalScore: 6
          errorDescription: errorDescription
          benchFailureRate: 6
          errorType: errorType
          latency: 7
          downScore: 9
          contractSuccess: true
          errorFull: errorFull
          up: 4
          down: 9
          upScore: 5
        lat: 5.962133916683182
        usedStorage: 7.061401241503109
        firstSeenBlock: 1
        ticks:
          total:
          - - 2.8841621266687802
            - 2.8841621266687802
          - - 2.8841621266687802
            - 2.8841621266687802
          bandwidth:
          - - 5.944895607614016
            - 5.944895607614016
          - - 5.944895607614016
            - 5.944895607614016
          used:
          - - 6.778324963048013
            - 6.778324963048013
          - - 6.778324963048013
            - 6.778324963048013
          storage:
          - - 6.878052220127876
            - 6.878052220127876
          - - 6.878052220127876
            - 6.878052220127876
          collateral:
          - - 6.704019297950036
            - 6.704019297950036
          - - 6.704019297950036
            - 6.704019297950036
        ip: ip
        storagePrice: 3.616076749251911
        version: version
        uploadPrice: 2.027123023002322
        downloadPrice: 4.145608029883936
        plotBands:
        - color: color
          from: 3
          to: 3
          label:
            textAlign: textAlign
            rotation: 7
            x: 0
            y: 7
            text: text
            align: align
        - color: color
          from: 3
          to: 3
          label:
            textAlign: textAlign
            rotation: 7
            x: 0
            y: 7
            text: text
            align: align
        online: true
        countryName: countryName
        sectorSize: 1
        collateral: 9.301444243932576
        requestStatus: requestStatus
        maxDuration: 5.637376656633329
        comparisonMatrix:
          price: 9.018348186070783
          contractPrice: 1.284659006116532
          stored: 8
          up: 3.5571952270680973
          collateral: 6.438423552598547
          down: 6.965117697638846
        pubkey: pubkey
      properties:
        requestStatus:
          type: string
        id:
          type: integer
        online:
          type: boolean
        rank:
          type: integer
        network:
          type: string
        pubkey:
          type: string
        ip:
          type: string
        lon:
          type: number
        lat:
          type: number
        isp:
          type: string
        countryCode:
          type: string
        countryName:
          type: string
        maxDuration:
          type: number
        totalStorage:
          type: number
        usedStorage:
          type: number
        collateral:
          type: number
        storagePrice:
          type: number
        uploadPrice:
          type: number
        downloadPrice:
          type: number
        minContractPrice:
          type: number
        firstSeenBlock:
          type: integer
        version:
          type: string
        sectorSize:
          type: integer
        windowSize:
          type: integer
        seenBy:
          items:
            type: string
          type: array
        benchmarks:
          $ref: '#/components/schemas/Benchmarks'
        comparisonMatrix:
          $ref: '#/components/schemas/ComparisonMatrix'
        ticks:
          $ref: '#/components/schemas/Ticks'
        plotBands:
          items:
            $ref: '#/components/schemas/PlotBand'
          type: array
        regionalScores:
          items:
            $ref: '#/components/schemas/RegionalScore'
          type: array
        uptime1m:
          type: number
        uptime6m:
          type: number
      type: object
    PlotBand_label:
      example:
        textAlign: textAlign
        rotation: 7
        x: 0
        y: 7
        text: text
        align: align
      properties:
        text:
          type: string
        rotation:
          type: integer
        textAlign:
          type: string
        align:
          type: string
        x:
          type: integer
        y:
          type: integer
